# Generated by Django 5.2.5 on 2025-11-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatmessage_emotion_chatmessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sentiment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='emotion',
            field=models.CharField(default='Neutral', max_length=20),
        ),
    ]
