# Generated by Django 5.2.5 on 2025-11-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chatmessage_sentiment_alter_chatmessage_emotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='sentiment',
        ),
    ]
