# Generated by Django 5.2.5 on 2025-11-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_directmessage_is_read_groupmessage_seen_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='group_icons/'),
        ),
    ]
