# Generated by Django 5.2.5 on 2025-11-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_group_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
